artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://archive.ics.uci.edu/static/public/102/thyroid+disease.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  ingestion_dir: artifacts/data_ingestion
  root_dir: artifacts/data_validation
  ALL_REQUIRED_FILES: ["allhypo","allhyper","ann","hypothyroid","sick-euthyroid","thyroid0387"]
  ann_columns : ["age","sex","on_thyroxine","query_on_thyroxine","on_antithyroid_medication","sick","pregnant","thyroid_surgery","I131_treatment","query_hypothyroid",
  "query_hyperthyroid","lithium","goitre","tumor","hypopituitary","psych","TSH","T3","TT4","T4U","FTI","class"]
  columns:
    - age
    - sex
    - on_thyroxine
    - query_on_thyroxine
    - on_antithyroid_medication
    - sick
    - pregnant
    - thyroid_surgery
    - I131_treatment
    - query_hypothyroid
    - query_hyperthyroid
    - lithium
    - goitre
    - tumor
    - hypopituitary
    - psych
    - TSH_measured
    - TSH
    - T3_measured
    - T3
    - TT4_measured
    - TT4
    - T4U_measured
    - T4U
    - FTI_measured
    - FTI
    - TBG_measured
    - TBG
    - referral_source
    - class

data_transformation:
  validation_dir: artifacts/data_validation
  root_dir: artifacts/data_transformation
  encoding_dir: artifacts/label_encoding
  data_dir: artifacts/data_transformation/transformed_data
  clustered_dir: artifacts/data_transformation/clustered_data
  cluster_model_dir: artifacts/models/cluster_model
  plot_dir: artifacts/plots
  categorical_columns: ['on_thyroxine', 'query_on_thyroxine', 'on_antithyroid_medication', 'sick', 'pregnant', 'thyroid_surgery', 'I131_treatment', 'query_hypothyroid','query_hyperthyroid', 'lithium', 'goitre', 'tumor', 'hypopituitary', 'psych']
  numerical_columns: ["age","TSH","T3","TT4","T4U","FTI"]
  drop_columns: ['TBG_measured', 'FTI_measured','TT4_measured', 'T3_measured','TSH_measured','T4U_measured','referral_source']
  categorical_columns_to_convert: [
    'sex','on_thyroxine', 'query_on_thyroxine', 'on_antithyroid_medication', 'sick', 'pregnant', 'thyroid_surgery', 'I131_treatment',
    'query_hypothyroid', 'query_hyperthyroid', 'lithium', 'goitre','tumor', 'hypopituitary', 'psych']
