artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://archive.ics.uci.edu/static/public/102/thyroid+disease.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  ingestion_dir: artifacts/data_ingestion
  root_dir: artifacts/data_validation
  ALL_REQUIRED_FILES: ["allhypo","allhyper","ann","hypothyroid","sick-euthyroid","thyroid0387"]
  ann_columns : ["age","sex","on_thyroxine","query_on_thyroxine","on_antithyroid_medication","sick","pregnant","thyroid_surgery","I131_treatment","query_hypothyroid",
  "query_hyperthyroid","lithium","goitre","tumor","hypopituitary","psych","TSH","T3","TT4","T4U","FTI","class"]
  columns:
    - age
    - sex
    - on_thyroxine
    - query_on_thyroxine
    - on_antithyroid_medication
    - sick
    - pregnant
    - thyroid_surgery
    - I131_treatment
    - query_hypothyroid
    - query_hyperthyroid
    - lithium
    - goitre
    - tumor
    - hypopituitary
    - psych
    - TSH_measured
    - TSH
    - T3_measured
    - T3
    - TT4_measured
    - TT4
    - T4U_measured
    - T4U
    - FTI_measured
    - FTI
    - TBG_measured
    - TBG
    - referral_source
    - class

